// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqiqlmlqdjnjbsqopmwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxaXFsbWxxZGpuamJzcW9wbXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NzQxNjQsImV4cCI6MjA1ODM1MDE2NH0.94914ILHwCR0t1gISlAouJwrAzZSU3-gkVHYPQTzIEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);